--- @module main
--- pasta ゴースト メインエントリーポイント
---
--- このファイルはゴースト初期化時に最初に実行されます。
--- scene_dic のファイナライズより先に実行されるため、
--- ユーザー定義の辞書登録や初期設定をここで行えます。
---
--- カスタマイズするには、user_scripts/main.lua を作成してください。
--- user_scripts/ は scripts/ より優先されます。
---
--- 使用例:
--- ```lua
--- -- user_scripts/main.lua
---
--- -- ユーザー定義のアクター辞書を登録
--- local WORD = require("pasta.word")
--- WORD.register_actor_dictionary("俺", {
---     一人称 = {"俺", "おれ", "オレ"},
---     二人称 = {"お前", "君"},
--- })
---
--- -- カスタム初期化処理
--- print("ゴースト初期化完了")
--- ```

-- デフォルト実装: 何もしない
return {}
