#!/bin/sh

cat << EOS
/* Generated by mkCombiningClassData.sh */
/* Generated from UCD version 5.2.0 */
package unicode;

class CombiningClassData {
    static var ccctable : IntHash<Int> = initCccTable();
    public static function get(key) {
        return ccctable.get(key);
    }
    static function initCccTable() {
        var table = new IntHash<Int>();
        var data : Array<Array<Int>> = [
EOS

cat UnicodeData.txt \
    | grep '[0-9A-F]\{4,5\};[^;]*;..;[1-9][0-9]*;.*' \
    | sed 's/\([0-9A-F]\{4,5\}\);[^;]*;..;\([1-9][0-9]*\);.*/\[0x\1,\2\],/'

cat << EOS
        ];
        for(c in data) {
            table.set(c[0], c[1]);
        }
        return table;
    }
}
EOS

