import _events = require("./shiori_api/events");
import _request = require("./shiori_api/request");
import _send = require("./shiori_api/send");
export declare var events: typeof _events.events;
export declare var request: typeof _request.request;
export declare var send: typeof _send;
export declare function version(): string;
export declare function name(): string;
export declare function craftman(): string;
export declare function craftmanw(): string;
export declare function useorigin1(): string;
