//! Producer-side source-map seam for the Lua code generator (R4: feasibility).
//!
//! This module defines ONLY the producer side of the `.pasta` <-> `.lua` source-map
//! seam: the [`SourceMapSink`] trait that the [`crate::code_gen::LuaCodeGenerator`]
//! calls to record `(generated_lua_line -> .pasta span)` correspondences, plus a
//! lightweight [`PastaPos`] position type for the seam.
//!
//! # Dependency direction (CRITICAL)
//!
//! The design's dependency direction is `debug -> code_gen`: the `debug` module
//! *consumes* the span material that `code_gen` produces. Therefore the producer
//! seam lives here in `code_gen` and `code_gen` MUST NOT depend on `debug`. The
//! concrete consumer-side `LineMap` / `resolve_lua_to_pasta` lives in
//! `debug/source_map.rs` (task 5.3, behind the `pasta-source-map-slice` feature) and
//! implements [`SourceMapSink`] to build its map from the records emitted here.
//!
//! # Feasibility seam, not a production map
//!
//! This is the R4 *feasibility* infrastructure proving the `.pasta` <-> `.lua` line
//! correspondence is resolvable (Requirement 4.1) through a real recording seam
//! (Requirement 4.2). Production-quality source-map output (full `generate_*`
//! coverage, always-on `.pasta` coordinates, bidirectional conversion) is an
//! out-of-boundary future spec (`pasta-source-map`).

use pasta_dsl::parser::Span;

/// A position in an original `.pasta` source file.
///
/// Used by the consumer side (task 5.3 `LineMap`) to express a resolved `.pasta`
/// coordinate. Kept in `code_gen` so the seam's vocabulary does not force `debug`
/// types into the generator (preserving the `debug -> code_gen` direction).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PastaPos {
    /// Originating `.pasta` file path (as known to the generator/loader).
    pub file: String,
    /// 1-based line number in the `.pasta` source.
    pub line: u32,
}

/// Sink that records `(generated_lua_line -> .pasta span)` correspondences.
///
/// The [`LuaCodeGenerator`](crate::code_gen::LuaCodeGenerator) calls
/// [`record`](SourceMapSink::record) for each generated Lua line whose originating
/// `.pasta` [`Span`] is known. `lua_line` is the 1-based line number of the emitted
/// output line (the generator's `out_line` value at the moment the line was written).
///
/// Implementors build whatever structure they need from the stream of records (e.g.
/// the consumer-side `LineMap` in `debug/source_map.rs`). When no sink is attached
/// (the default for ALL production transpile callers) the seam is inert and the
/// generated bytes are unchanged.
pub trait SourceMapSink {
    /// Record that generated Lua line `lua_line` (1-based) originates from `span`.
    fn record(&mut self, lua_line: u32, span: Span);
}
