--- @module pasta.shiori.event.register
--- イベントハンドラ登録テーブル
---
--- ゴースト開発者がイベントハンドラを登録するためのテーブル。
--- 依存モジュールなし（循環参照回避のため）。
---
--- ハンドラシグネチャ（EVENT.fire は act オブジェクトを渡す）:
---   function(act: ShioriAct) -> string|thread|nil
---
--- act.req テーブル構造（Rust側 parse_request() により生成）:
---   - req.id: イベント名（例: "OnBoot", "OnClose"）
---   - req.method: "get" | "notify"
---   - req.version: 30（SHIORI/3.0）
---   - req.charset: 文字セット（例: "UTF-8"）
---   - req.sender: 送信者名（例: "SSP"）
---   - req.reference: 参照テーブル（reference[0], reference[1], ...）
---   - req.dic: 全ヘッダー辞書
---
--- 注意: act.req テーブルはread-only契約。ハンドラ内で変更しないこと。
---
--- 戻り値の規則（EVENT.fire が応答にする）:
---   - "SHIORI/" で始まる文字列: RES で作った応答全体としてそのまま返す（204・311・312・500 も可）
---   - それ以外の文字列: Value の 200（空文字列なら 204）
---   - nil: 204
---   - thread: EVENT.drive で再開し、出力を接頭辞にかかわらず常に Value の 200 にする（出力が無ければ 204）
---
--- 使用例:
--- ```lua
--- local REG = require("pasta.shiori.event.register")
---
--- -- 返した文字列は Value の 200 になる（SHIORI/ で始まる文字列は応答全体としてそのまま返る）
--- REG.OnBoot = function(act)
---     return [[\0\s[0]こんにちは\e]]
--- end
---
--- REG.OnClose = function(act)
---     return [[\0\s[0]さようなら\e]]
--- end
---
--- REG.OnMouseDoubleClick = function(act)
---     return [[\0\s[0]なあに？\e]]
--- end
--- ```

--- @type table<string, fun(act: table): string|thread|nil>
local REG = {}

return REG
