[package]
name = "pasta_lsp"
workspace = "../.."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = true
description = "Pasta DSL - Language Server Protocol implementation"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pasta_dsl.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-lsp.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true
