-- Auto-generated by pasta_lua CacheManager
-- Do not edit manually
-- Generated at: 1770027528 (unix timestamp)

require("pasta.scene.actors")
require("pasta.scene.boot")
require("pasta.scene.click")
require("pasta.scene.talk")

require("pasta").finalize_scene()
